platform :ios, ‘8.0’

target 'DeDaoSwift' do

  use_frameworks!

pod 'SnapKit'
pod 'Kingfisher'
pod 'ReactiveSwift'
pod 'ObjectMapper'
pod 'Alamofire'
pod 'MJRefresh'
pod 'CYLTabBarController'
pod 'RxSwift'
#pod 'ReactiveCocoa'
pod 'UIColor_Hex_Swift', '~> 3.0.2'
pod 'GDPerformanceView-Swift'
end
