platform :ios, ‘8.0’

target 'DeDaoSwift' do

  use_frameworks!

pod 'SnapKit'
pod 'Kingfisher'
pod 'ReactiveSwift'
pod 'ObjectMapper'
pod 'Alamofire'
pod 'MJRefresh'
pod 'CYLTabBarController'
pod 'RxSwift'
pod 'ReactiveCocoa'
end
